name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'develop'
        type: choice
        options:
          - main
          - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports: [5432:5432]
        options: |
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      DJANGO_SETTINGS_MODULE: huijia.settings
      SECRET_KEY: testkey
      DEBUG: 'True'

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    # 缓存 pip 依赖
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # 缓存 Python 包
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/lib/python3.10/site-packages
          ~/.local/bin
        key: ${{ runner.os }}-python-packages-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-packages-

    # 缓存测试结果
    - name: Cache test results
      uses: actions/cache@v3
      with:
        path: |
          .pytest_cache
          .coverage
          coverage.xml
        key: ${{ runner.os }}-test-results-${{ hashFiles('**/requirements.txt', '**/core/tests/**') }}
        restore-keys: |
          ${{ runner.os }}-test-results-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        pytest -v --ds=huijia.settings
